// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/pujidjayanto/goginboilerplate/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// MakePurchase provides a mock function with given fields: _a0, _a1
func (_m *Service) MakePurchase(_a0 context.Context, _a1 dto.CreatePurchaseRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MakePurchase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatePurchaseRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_MakePurchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePurchase'
type Service_MakePurchase_Call struct {
	*mock.Call
}

// MakePurchase is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 dto.CreatePurchaseRequest
func (_e *Service_Expecter) MakePurchase(_a0 interface{}, _a1 interface{}) *Service_MakePurchase_Call {
	return &Service_MakePurchase_Call{Call: _e.mock.On("MakePurchase", _a0, _a1)}
}

func (_c *Service_MakePurchase_Call) Run(run func(_a0 context.Context, _a1 dto.CreatePurchaseRequest)) *Service_MakePurchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreatePurchaseRequest))
	})
	return _c
}

func (_c *Service_MakePurchase_Call) Return(_a0 error) *Service_MakePurchase_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_MakePurchase_Call) RunAndReturn(run func(context.Context, dto.CreatePurchaseRequest) error) *Service_MakePurchase_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
